NAME	= libft.a

SRCS	=	ft_bzero.c \
			ft_isalnum.c \
			ft_isalpha.c \
			ft_isascii.c \
			ft_isdigit.c \
			ft_isprint.c \
			ft_memcpy.c \
			ft_memset.c \
			ft_memmove.c \
			ft_memchr.c \
			ft_memcmp.c \
			ft_calloc.c \
			ft_strchr.c \
			ft_strlcat.c \
			ft_strlcpy.c \
			ft_strlen.c \
			ft_strncmp.c \
			ft_strnstr.c \
			ft_atoi.c \
			ft_strrchr.c \
			ft_tolower.c \
			ft_toupper.c \
			ft_strdup.c \
			ft_strjoin.c \
			ft_strtrim.c \
			ft_substr.c \
			ft_split.c \
			ft_itoa.c \
			ft_putchar_fd.c \
			ft_putendl_fd.c \
			ft_putnbr_fd.c \
			ft_putstr_fd.c \
			ft_strmapi.c \
			ft_striteri.c

SRCS_B	=	ft_lstnew.c \
			ft_lstadd_back.c \
			ft_lstadd_front.c \
			ft_lstsize.c \
			ft_lstdelone.c \
			ft_lstclear.c \
			ft_lstiter.c \
			ft_lstmap.c \
			ft_lstlast.c

OBJS	= $(SRCS:.c=.o)

OBJS_B	= $(SRCS_B:.c=.o)

CFLAGS	= -Wall -Werror -Wextra

CC 		= gcc

${NAME}: ${OBJS}
	${CC} ${CFLAGS} -c ${SRCS}
	ar rcs ${NAME} ${OBJS}

all: ${NAME}

clean:
	rm -f ${OBJS} ${OBJS_B}

fclean: clean
	rm -f $(NAME)

re: fclean all bonus

bonus: ${OBJS_B}
	${CC} ${CFLAGS} -c ${SRCS_B}
	ar rcs ${NAME} ${OBJS_B}

.PHONY: all bonus clean fclean re