#!/bin/bash
echo "EXECUTING: ./fdf"
./fdf test_maps/t1.fdf test_maps/t2.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/t1.fdf test_maps/t2.fdf"
./fdf test_maps/t1.fdf test_maps/t2.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/not_existing_map"
./fdf test_maps/not_existing_map
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/not_existing_map1 test_maps/not_existing_map1"
./fdf test_maps/not_existing_map1 test_maps/not_existing_map1
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/empty.fdf"
./fdf test_maps/empty.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/empty_nl.fdf"
./fdf test_maps/empty_nl.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/10-2.fdf"
./fdf test_maps/10-2.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/10-70.fdf"
./fdf test_maps/10-70.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/100-6.fdf"
./fdf test_maps/100-6.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/20-60.fdf"
./fdf test_maps/20-60.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/42.fdf"
./fdf test_maps/42.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/50-4.fdf"
./fdf test_maps/50-4.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/basictest.fdf"
./fdf test_maps/basictest.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/elem-col.fdf"
./fdf test_maps/elem-col.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/elem-fract.fdf"
./fdf test_maps/elem-fract.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/elem.fdf"
./fdf test_maps/elem.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/elem2.fdf"
./fdf test_maps/elem2.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/julia.fdf"
./fdf test_maps/julia.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/mars.fdf"
./fdf test_maps/mars.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/pentenegpos.fdf"
./fdf test_maps/pentenegpos.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/plat.fdf"
./fdf test_maps/plat.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/pnp_flat.fdf"
./fdf test_maps/pnp_flat.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/pylone.fdf"
./fdf test_maps/pylone.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/pyra.fdf"
./fdf test_maps/pyra.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/pyramide.fdf"
./fdf test_maps/pyramide.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/t1.fdf"
./fdf test_maps/t1.fdf
echo 
echo
echo
echo "EXECUTING: ./fdf test_maps/t2.fdf"
./fdf test_maps/t2.fdf

